// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: config/v1/config.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetConfig Messages
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                       // Auth token
	ConfigVersion int32                  `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // Client's current config version (0 = first request)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetConfigRequest) GetConfigVersion() int32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkCidr   string                 `protobuf:"bytes,1,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`        // VPN network CIDR (e.g., "10.8.0.0/16")
	Mtu           int32                  `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`                                          // Maximum transmission unit
	DnsServers    []string               `protobuf:"bytes,3,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`           // DNS servers for VPN
	ConfigVersion int32                  `protobuf:"varint,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // Current config version
	UpToDate      bool                   `protobuf:"varint,5,opt,name=up_to_date,json=upToDate,proto3" json:"up_to_date,omitempty"`              // True if client already has latest config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

func (x *GetConfigResponse) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *GetConfigResponse) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *GetConfigResponse) GetConfigVersion() int32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *GetConfigResponse) GetUpToDate() bool {
	if x != nil {
		return x.UpToDate
	}
	return false
}

// RequestIP Messages
type RequestIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                 // Auth token
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Node requesting IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestIPRequest) Reset() {
	*x = RequestIPRequest{}
	mi := &file_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestIPRequest) ProtoMessage() {}

func (x *RequestIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestIPRequest.ProtoReflect.Descriptor instead.
func (*RequestIPRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *RequestIPRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestIPRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RequestIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`    // Allocated IP (e.g., "10.8.0.5")
	SubnetMask    string                 `protobuf:"bytes,2,opt,name=subnet_mask,json=subnetMask,proto3" json:"subnet_mask,omitempty"` // Subnet mask
	Gateway       string                 `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`                         // Gateway IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestIPResponse) Reset() {
	*x = RequestIPResponse{}
	mi := &file_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestIPResponse) ProtoMessage() {}

func (x *RequestIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestIPResponse.ProtoReflect.Descriptor instead.
func (*RequestIPResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *RequestIPResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RequestIPResponse) GetSubnetMask() string {
	if x != nil {
		return x.SubnetMask
	}
	return ""
}

func (x *RequestIPResponse) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

// ReleaseIP Messages
type ReleaseIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                          // Auth token
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // Node releasing IP
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // IP to release
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPRequest) Reset() {
	*x = ReleaseIPRequest{}
	mi := &file_config_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPRequest) ProtoMessage() {}

func (x *ReleaseIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPRequest.ProtoReflect.Descriptor instead.
func (*ReleaseIPRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseIPRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReleaseIPRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReleaseIPRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type ReleaseIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIPResponse) Reset() {
	*x = ReleaseIPResponse{}
	mi := &file_config_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIPResponse) ProtoMessage() {}

func (x *ReleaseIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIPResponse.ProtoReflect.Descriptor instead.
func (*ReleaseIPResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseIPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseIPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_config_v1_config_proto protoreflect.FileDescriptor

const file_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16config/v1/config.proto\x12\tconfig.v1\"O\n" +
	"\x10GetConfigRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x05R\rconfigVersion\"\xae\x01\n" +
	"\x11GetConfigResponse\x12!\n" +
	"\fnetwork_cidr\x18\x01 \x01(\tR\vnetworkCidr\x12\x10\n" +
	"\x03mtu\x18\x02 \x01(\x05R\x03mtu\x12\x1f\n" +
	"\vdns_servers\x18\x03 \x03(\tR\n" +
	"dnsServers\x12%\n" +
	"\x0econfig_version\x18\x04 \x01(\x05R\rconfigVersion\x12\x1c\n" +
	"\n" +
	"up_to_date\x18\x05 \x01(\bR\bupToDate\"A\n" +
	"\x10RequestIPRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"m\n" +
	"\x11RequestIPResponse\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vsubnet_mask\x18\x02 \x01(\tR\n" +
	"subnetMask\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\"`\n" +
	"\x10ReleaseIPRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\"G\n" +
	"\x11ReleaseIPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe7\x01\n" +
	"\rConfigService\x12F\n" +
	"\tGetConfig\x12\x1b.config.v1.GetConfigRequest\x1a\x1c.config.v1.GetConfigResponse\x12F\n" +
	"\tRequestIP\x12\x1b.config.v1.RequestIPRequest\x1a\x1c.config.v1.RequestIPResponse\x12F\n" +
	"\tReleaseIP\x12\x1b.config.v1.ReleaseIPRequest\x1a\x1c.config.v1.ReleaseIPResponseBAZ?github.com/saitddundar/gordion-vpn/pkg/proto/config/v1;configv1b\x06proto3"

var (
	file_config_v1_config_proto_rawDescOnce sync.Once
	file_config_v1_config_proto_rawDescData []byte
)

func file_config_v1_config_proto_rawDescGZIP() []byte {
	file_config_v1_config_proto_rawDescOnce.Do(func() {
		file_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)))
	})
	return file_config_v1_config_proto_rawDescData
}

var file_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_config_v1_config_proto_goTypes = []any{
	(*GetConfigRequest)(nil),  // 0: config.v1.GetConfigRequest
	(*GetConfigResponse)(nil), // 1: config.v1.GetConfigResponse
	(*RequestIPRequest)(nil),  // 2: config.v1.RequestIPRequest
	(*RequestIPResponse)(nil), // 3: config.v1.RequestIPResponse
	(*ReleaseIPRequest)(nil),  // 4: config.v1.ReleaseIPRequest
	(*ReleaseIPResponse)(nil), // 5: config.v1.ReleaseIPResponse
}
var file_config_v1_config_proto_depIdxs = []int32{
	0, // 0: config.v1.ConfigService.GetConfig:input_type -> config.v1.GetConfigRequest
	2, // 1: config.v1.ConfigService.RequestIP:input_type -> config.v1.RequestIPRequest
	4, // 2: config.v1.ConfigService.ReleaseIP:input_type -> config.v1.ReleaseIPRequest
	1, // 3: config.v1.ConfigService.GetConfig:output_type -> config.v1.GetConfigResponse
	3, // 4: config.v1.ConfigService.RequestIP:output_type -> config.v1.RequestIPResponse
	5, // 5: config.v1.ConfigService.ReleaseIP:output_type -> config.v1.ReleaseIPResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_v1_config_proto_init() }
func file_config_v1_config_proto_init() {
	if File_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_config_proto_goTypes,
		DependencyIndexes: file_config_v1_config_proto_depIdxs,
		MessageInfos:      file_config_v1_config_proto_msgTypes,
	}.Build()
	File_config_v1_config_proto = out.File
	file_config_v1_config_proto_goTypes = nil
	file_config_v1_config_proto_depIdxs = nil
}
