// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: discovery/v1/discovery.proto

package discoveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Peer info
type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // Node ID
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // Public IP address
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                           // Listen port
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`                        // Geographic region (e.g., "eu-west")
	Bandwidth     int64                  `protobuf:"varint,5,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`                 // Available bandwidth (bytes/sec)
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`   // Last heartbeat timestamp
	PeerId        string                 `protobuf:"bytes,7,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`          // libp2p PeerID
	P2PAddrs      []string               `protobuf:"bytes,8,rep,name=p2p_addrs,json=p2pAddrs,proto3" json:"p2p_addrs,omitempty"`    // libp2p Multiaddrs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Peer) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Peer) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Peer) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Peer) GetBandwidth() int64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *Peer) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *Peer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Peer) GetP2PAddrs() []string {
	if x != nil {
		return x.P2PAddrs
	}
	return nil
}

// ListPeers Messages
type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"` // Filter by region (optional)
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // Max peers to return (default: 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *ListPeersRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListPeersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"` // List of available peers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *ListPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// RegisterPeer Messages
type RegisterPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                          // Auth token from Identity Service
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // This node's public IP
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                           // Listen port
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`                        // Geographic region
	Bandwidth     int64                  `protobuf:"varint,5,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`                 // Available bandwidth
	PeerId        string                 `protobuf:"bytes,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`          // libp2p PeerID
	P2PAddrs      []string               `protobuf:"bytes,7,rep,name=p2p_addrs,json=p2pAddrs,proto3" json:"p2p_addrs,omitempty"`    // libp2p Multiaddrs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerRequest) Reset() {
	*x = RegisterPeerRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerRequest) ProtoMessage() {}

func (x *RegisterPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerRequest.ProtoReflect.Descriptor instead.
func (*RegisterPeerRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterPeerRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterPeerRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterPeerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterPeerRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterPeerRequest) GetBandwidth() int64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *RegisterPeerRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *RegisterPeerRequest) GetP2PAddrs() []string {
	if x != nil {
		return x.P2PAddrs
	}
	return nil
}

type RegisterPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerResponse) Reset() {
	*x = RegisterPeerResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerResponse) ProtoMessage() {}

func (x *RegisterPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerResponse.ProtoReflect.Descriptor instead.
func (*RegisterPeerResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterPeerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat Messages
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`          // Auth token
	Bandwidth     int64                  `protobuf:"varint,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"` // Current available bandwidth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetBandwidth() int64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Ttl           int64                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"` // Time to live (seconds until next heartbeat)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_discovery_v1_discovery_proto protoreflect.FileDescriptor

const file_discovery_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"\x1cdiscovery/v1/discovery.proto\x12\fdiscovery.v1\"\xdb\x01\n" +
	"\x04Peer\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1c\n" +
	"\tbandwidth\x18\x05 \x01(\x03R\tbandwidth\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\x12\x17\n" +
	"\apeer_id\x18\a \x01(\tR\x06peerId\x12\x1b\n" +
	"\tp2p_addrs\x18\b \x03(\tR\bp2pAddrs\"@\n" +
	"\x10ListPeersRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"=\n" +
	"\x11ListPeersResponse\x12(\n" +
	"\x05peers\x18\x01 \x03(\v2\x12.discovery.v1.PeerR\x05peers\"\xca\x01\n" +
	"\x13RegisterPeerRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1c\n" +
	"\tbandwidth\x18\x05 \x01(\x03R\tbandwidth\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tp2p_addrs\x18\a \x03(\tR\bp2pAddrs\"J\n" +
	"\x14RegisterPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x10HeartbeatRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1c\n" +
	"\tbandwidth\x18\x02 \x01(\x03R\tbandwidth\"?\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x03R\x03ttl2\x85\x02\n" +
	"\x10DiscoveryService\x12L\n" +
	"\tListPeers\x12\x1e.discovery.v1.ListPeersRequest\x1a\x1f.discovery.v1.ListPeersResponse\x12U\n" +
	"\fRegisterPeer\x12!.discovery.v1.RegisterPeerRequest\x1a\".discovery.v1.RegisterPeerResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.discovery.v1.HeartbeatRequest\x1a\x1f.discovery.v1.HeartbeatResponseBGZEgithub.com/saitddundar/gordion-vpn/pkg/proto/discovery/v1;discoveryv1b\x06proto3"

var (
	file_discovery_v1_discovery_proto_rawDescOnce sync.Once
	file_discovery_v1_discovery_proto_rawDescData []byte
)

func file_discovery_v1_discovery_proto_rawDescGZIP() []byte {
	file_discovery_v1_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_v1_discovery_proto_rawDesc), len(file_discovery_v1_discovery_proto_rawDesc)))
	})
	return file_discovery_v1_discovery_proto_rawDescData
}

var file_discovery_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_discovery_v1_discovery_proto_goTypes = []any{
	(*Peer)(nil),                 // 0: discovery.v1.Peer
	(*ListPeersRequest)(nil),     // 1: discovery.v1.ListPeersRequest
	(*ListPeersResponse)(nil),    // 2: discovery.v1.ListPeersResponse
	(*RegisterPeerRequest)(nil),  // 3: discovery.v1.RegisterPeerRequest
	(*RegisterPeerResponse)(nil), // 4: discovery.v1.RegisterPeerResponse
	(*HeartbeatRequest)(nil),     // 5: discovery.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 6: discovery.v1.HeartbeatResponse
}
var file_discovery_v1_discovery_proto_depIdxs = []int32{
	0, // 0: discovery.v1.ListPeersResponse.peers:type_name -> discovery.v1.Peer
	1, // 1: discovery.v1.DiscoveryService.ListPeers:input_type -> discovery.v1.ListPeersRequest
	3, // 2: discovery.v1.DiscoveryService.RegisterPeer:input_type -> discovery.v1.RegisterPeerRequest
	5, // 3: discovery.v1.DiscoveryService.Heartbeat:input_type -> discovery.v1.HeartbeatRequest
	2, // 4: discovery.v1.DiscoveryService.ListPeers:output_type -> discovery.v1.ListPeersResponse
	4, // 5: discovery.v1.DiscoveryService.RegisterPeer:output_type -> discovery.v1.RegisterPeerResponse
	6, // 6: discovery.v1.DiscoveryService.Heartbeat:output_type -> discovery.v1.HeartbeatResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_discovery_v1_discovery_proto_init() }
func file_discovery_v1_discovery_proto_init() {
	if File_discovery_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_v1_discovery_proto_rawDesc), len(file_discovery_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_v1_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_v1_discovery_proto_depIdxs,
		MessageInfos:      file_discovery_v1_discovery_proto_msgTypes,
	}.Build()
	File_discovery_v1_discovery_proto = out.File
	file_discovery_v1_discovery_proto_goTypes = nil
	file_discovery_v1_discovery_proto_depIdxs = nil
}
