package cmd

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"golang.org/x/crypto/curve25519"
)

var initForce bool

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize Gordion VPN configuration",
	Long: styleBold.Render("gordion init") + "\n" +
		styleDim.Render("Generates a WireGuard keypair and creates a default config.yaml.\n") +
		styleDim.Render("Private key is stored separately with 0600 permissions — never in the config file.\n") +
		styleDim.Render("Run this once before your first `gordion up`."),
	RunE: func(cmd *cobra.Command, args []string) error {
		// Determine paths
		home, _ := os.UserHomeDir()
		keysDir := filepath.Join(home, ".gordion", "keys")
		privKeyFile := filepath.Join(keysDir, "private.key")
		pubKeyFile := filepath.Join(keysDir, "public.key")

		outDir := "configs"
		outFile := filepath.Join(outDir, "agent.yaml")
		if cfgFile != "" {
			outFile = cfgFile
			outDir = filepath.Dir(outFile)
		}

		if _, err := os.Stat(outFile); err == nil && !initForce {
			printWarn("Config already exists: " + outFile)
			fmt.Printf("  %s\n\n", styleDim.Render("Use --force to overwrite."))
			return nil
		}

		fmt.Println()
		fmt.Printf("  %s %s\n\n",
			styleTitle.Render("Gordion VPN"),
			styleDim.Render("— initializing"),
		)

		// 1. Generate WireGuard keypair
		privKey, pubKey, err := generateWireGuardKeys()
		if err != nil {
			return fmt.Errorf("generate keypair: %w", err)
		}

		// 2. Write private key to secure location (NEVER in config file)
		if err := os.MkdirAll(keysDir, 0700); err != nil {
			return fmt.Errorf("create keys dir: %w", err)
		}
		if err := os.WriteFile(privKeyFile, []byte(privKey+"\n"), 0600); err != nil {
			return fmt.Errorf("write private key: %w", err)
		}
		if err := os.WriteFile(pubKeyFile, []byte(pubKey+"\n"), 0644); err != nil {
			return fmt.Errorf("write public key: %w", err)
		}
		printOK("WireGuard keypair saved to " + styleBold.Render(keysDir))
		printOK("Private key permissions: " + styleBold.Render("0600") + styleDim.Render(" (not committed to git)"))

		// 3. Create config directory and write config (public key only, no private key)
		if err := os.MkdirAll(outDir, 0700); err != nil {
			return fmt.Errorf("create config dir: %w", err)
		}
		config := buildDefaultConfig(pubKeyFile, pubKey)
		if err := os.WriteFile(outFile, []byte(config), 0600); err != nil {
			return fmt.Errorf("write config: %w", err)
		}
		printOK("Config file created: " + styleBold.Render(outFile))

		// 4. Summary
		fmt.Println()
		fmt.Printf("  %s\n", styleBold.Render("Public Key:"))
		fmt.Printf("  %s\n\n", styleDim.Render(pubKey))
		fmt.Printf("  %s\n", styleDim.Render("Private Key: "+privKeyFile+" (keep this secret)"))
		fmt.Println()
		fmt.Printf("  %s\n",
			styleDim.Render("Edit "+outFile+" to set your service addresses, then run:"),
		)
		fmt.Printf("  %s\n\n",
			styleBold.Render("  gordion up"),
		)

		return nil
	},
}

func generateWireGuardKeys() (privB64, pubB64 string, err error) {
	var priv [32]byte
	if _, err = rand.Read(priv[:]); err != nil {
		return
	}

	// WireGuard key clamping (RFC 7748)
	priv[0] &= 248
	priv[31] &= 127
	priv[31] |= 64

	// X25519 scalar multiplication (replaces deprecated ScalarBaseMult)
	pub, e := curve25519.X25519(priv[:], curve25519.Basepoint)
	if e != nil {
		err = e
		return
	}

	privB64 = base64.StdEncoding.EncodeToString(priv[:])
	pubB64 = base64.StdEncoding.EncodeToString(pub)
	return
}

func buildDefaultConfig(privKeyPath, pubKey string) string {
	lines := []string{
		"# Gordion VPN — Agent Configuration",
		"# Generated by `gordion init`",
		"# ",
		"# ⚠ private_key_file contains your WireGuard private key.",
		"#   Do NOT commit it to version control.",
		"",
		"# Control plane addresses (change to your server IPs/hostnames)",
		"identity_addr:  \"localhost:8001\"",
		"discovery_addr: \"localhost:8002\"",
		"config_addr:    \"localhost:8003\"",
		"",
		"log_level: \"info\"",
		"heartbeat_interval: 25",
		"",
		"# WireGuard",
		"wireguard_port: 51820",
		"private_key_file: \"" + privKeyPath + "\"",
		"# public_key: \"" + pubKey + "\"",
		"dry_run: true   # set false for a real tunnel (requires WireGuard installed)",
		"",
		"# libp2p",
		"p2p_port: 4001",
		"",
		"# TLS (leave empty for insecure local dev)",
		"# tls_ca_cert: \"certs/ca-cert.pem\"",
		"",
		"# Exit Node",
		"is_exit_node:  false",
		"use_exit_node: false",
		"exit_node_id:  \"\"",
		"exit_node_dns: \"1.1.1.1, 1.0.0.1\"",
	}
	return strings.Join(lines, "\n") + "\n"
}

func init() {
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing config file")
	rootCmd.AddCommand(initCmd)
}
