package cmd

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"golang.org/x/crypto/curve25519"
)

var initForce bool

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize Gordion VPN configuration",
	Long: styleBold.Render("gordion init") + "\n" +
		styleDim.Render("Generates a WireGuard keypair and creates a default config.yaml.\n") +
		styleDim.Render("Run this once before your first `gordion up`."),
	RunE: func(cmd *cobra.Command, args []string) error {
		outDir := "configs"
		outFile := filepath.Join(outDir, "agent.yaml")

		// Respect --config flag as output target
		if cfgFile != "" {
			outFile = cfgFile
			outDir = filepath.Dir(outFile)
		}

		if _, err := os.Stat(outFile); err == nil && !initForce {
			printWarn(fmt.Sprintf("Config already exists: %s", outFile))
			fmt.Printf("  %s\n\n", styleDim.Render("Use --force to overwrite."))
			return nil
		}

		fmt.Println()
		fmt.Printf("  %s %s\n\n",
			styleTitle.Render("Gordion VPN"),
			styleDim.Render("— initializing"),
		)

		// 1. Generate WireGuard keypair (Curve25519)
		privKey, pubKey, err := generateWireGuardKeys()
		if err != nil {
			return fmt.Errorf("generate keypair: %w", err)
		}
		printOK("WireGuard keypair generated")

		// 2. Create output directory
		if err := os.MkdirAll(outDir, 0700); err != nil {
			return fmt.Errorf("create config dir: %w", err)
		}

		// 3. Write config file
		config := buildDefaultConfig(privKey, pubKey)
		if err := os.WriteFile(outFile, []byte(config), 0600); err != nil {
			return fmt.Errorf("write config: %w", err)
		}
		printOK("Config file created: " + styleBold.Render(outFile))

		// 4. Summary
		fmt.Println()
		fmt.Printf("  %s\n", styleBold.Render("Public Key:"))
		fmt.Printf("  %s\n\n", styleDim.Render(pubKey))

		fmt.Printf("  %s\n",
			styleDim.Render("Edit "+outFile+" to set your service addresses, then run:"),
		)
		fmt.Printf("  %s\n\n",
			styleBold.Render("  gordion up"),
		)

		return nil
	},
}

// generateWireGuardKeys generates a Curve25519 private+public keypair (WireGuard format).
func generateWireGuardKeys() (privB64, pubB64 string, err error) {
	var priv [32]byte
	if _, err = rand.Read(priv[:]); err != nil {
		return
	}

	// WireGuard clamping
	priv[0] &= 248
	priv[31] &= 127
	priv[31] |= 64

	var pub [32]byte
	curve25519.ScalarBaseMult(&pub, &priv)

	privB64 = base64.StdEncoding.EncodeToString(priv[:])
	pubB64 = base64.StdEncoding.EncodeToString(pub[:])
	return
}

// buildDefaultConfig returns a ready-to-use agent YAML config string.
func buildDefaultConfig(privKey, pubKey string) string {
	lines := []string{
		"# Gordion VPN — Agent Configuration",
		"# Generated by `gordion init`",
		"",
		"# Control plane addresses (change to your server IPs/hostnames)",
		"identity_addr:  \"localhost:8001\"",
		"discovery_addr: \"localhost:8002\"",
		"config_addr:    \"localhost:8003\"",
		"",
		"log_level: \"info\"",
		"heartbeat_interval: 25",
		"",
		"# WireGuard",
		fmt.Sprintf("wireguard_port: 51820"),
		fmt.Sprintf("# private_key: \"%s\"", privKey),
		fmt.Sprintf("# public key:  \"%s\"", pubKey),
		"dry_run: true   # set false for a real tunnel (requires WireGuard installed)",
		"",
		"# libp2p",
		"p2p_port: 4001",
		"",
		"# TLS (leave empty for insecure local dev)",
		"# tls_ca_cert: \"certs/ca-cert.pem\"",
		"",
		"# Exit Node",
		"is_exit_node:  false",
		"use_exit_node: false",
		"exit_node_id:  \"\"",
		"exit_node_dns: \"1.1.1.1, 1.0.0.1\"",
	}
	return strings.Join(lines, "\n") + "\n"
}

func init() {
	initCmd.Flags().BoolVar(&initForce, "force", false, "Overwrite existing config file")
	rootCmd.AddCommand(initCmd)
}
